manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: hh
      url-base: https://github.com/hh
  projects:
    - name: zmk
      remote: hh
      revision: feat/hogp-central
      import: app/west.yml
  self:
    path: config
