manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: hh
      url-base: https://github.com/hh
  projects:
    - name: zmk
      remote: refil
      revision: adv360-z3.5-2
      import: app/west.yml
    - name: zmk-hogp
      remote: hh
      revision: b87899f3d5b3ba8954a384f4c0837a1e8bbc4448
      import: false
  self:
    path: config
